-- order_management_schema.sql
-- Database schema for Order Management functionality
-- Database System: PostgreSQL

-- Ensure UUID generation extension is available
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-------------------------------------
--      ORDER MANAGEMENT MODULE    --
-------------------------------------

-- 1. Define order_status ENUM Type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status_enum') THEN
        CREATE TYPE order_status_enum AS ENUM (
            'pending_payment', -- Cart checkout complete, awaiting payment confirmation
            'payment_failed',  -- Payment was attempted but failed
            'pending_confirmation', -- Payment confirmed, awaiting final order confirmation (e.g. stock check, fraud review)
            'confirmed',       -- Order confirmed, ready for processing
            'processing',      -- Order is being prepared for shipment
            'shipped',         -- Order has been shipped
            'delivered',       -- Order has been delivered (future: requires delivery confirmation)
            'cancelled_by_user', -- Order cancelled by the user
            'cancelled_by_admin',-- Order cancelled by an administrator
            'refunded',        -- Order has been refunded (partially or fully)
            'completed'        -- Order fulfilled and no further action expected (alternative to delivered if no separate delivery tracking)
        );
        COMMENT ON TYPE order_status_enum IS 'Defines the possible statuses for an order throughout its lifecycle.';
    END IF;
END$$;


-- 2. orders Table
CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_number TEXT UNIQUE NOT NULL, -- User-friendly unique order ID (e.g., ORD-YYYYMMDD-XXXXX), generated by application
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, -- Orders must belong to a registered user. RESTRICT deletion of user if they have orders.
    cart_id UUID UNIQUE NOT NULL REFERENCES shopping_carts(id) ON DELETE RESTRICT, -- Cart converted to this order. RESTRICT deletion of cart if it became an order.
    
    order_total NUMERIC(12, 2) NOT NULL CHECK (order_total >= 0), -- Total amount for the order
    subtotal NUMERIC(12, 2) NOT NULL CHECK (subtotal >= 0), -- Sum of (price_paid_per_unit * quantity) for all items
    shipping_cost NUMERIC(10, 2) DEFAULT 0.00 CHECK (shipping_cost >= 0),
    taxes_total NUMERIC(10, 2) DEFAULT 0.00 CHECK (taxes_total >= 0),
    discount_total NUMERIC(10, 2) DEFAULT 0.00 CHECK (discount_total >= 0),

    shipping_address JSONB NOT NULL,
    billing_address JSONB NOT NULL,
    
    order_status order_status_enum NOT NULL DEFAULT 'pending_payment',
    
    payment_gateway TEXT, -- e.g., 'stripe', 'paypal'
    payment_intent_id TEXT UNIQUE, -- ID from the payment gateway, unique if present
    payment_status TEXT, -- e.g., 'succeeded', 'pending', 'failed' (more granular than order_status)

    notes_to_customer TEXT,
    internal_notes TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE orders IS 'Stores customer order information.';
COMMENT ON COLUMN orders.order_number IS 'User-friendly unique identifier for the order, generated by the application.';
COMMENT ON COLUMN orders.user_id IS 'Foreign key referencing the user who placed the order.';
COMMENT ON COLUMN orders.cart_id IS 'Foreign key referencing the shopping cart that was converted into this order. Ensures a cart is used for only one order.';
COMMENT ON COLUMN orders.order_total IS 'The final total amount paid for the order (including items, shipping, taxes, minus discounts).';
COMMENT ON COLUMN orders.subtotal IS 'Total price of all items before shipping, taxes, and discounts.';
COMMENT ON COLUMN orders.shipping_address IS 'JSONB object storing the structured shipping address.';
COMMENT ON COLUMN orders.billing_address IS 'JSONB object storing the structured billing address.';
COMMENT ON COLUMN orders.order_status IS 'Current status of the order using the order_status_enum type.';
COMMENT ON COLUMN orders.payment_intent_id IS 'Transaction or intent ID from the payment processor.';
COMMENT ON COLUMN orders.payment_status IS 'Specific status from the payment processor.';


-- 3. order_items Table
CREATE TABLE order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE, -- If an order is deleted, its items are also deleted.
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, -- Prevent product deletion if it's part of any order.
    
    quantity INT NOT NULL CHECK (quantity > 0),
    price_paid_per_unit NUMERIC(10, 2) NOT NULL CHECK (price_paid_per_unit >= 0), -- Price per unit at the time of order
    
    -- Optional: Store some product details at time of order for historical accuracy,
    -- in case product details change later (name, sku, etc.)
    product_name_at_order TEXT,
    product_sku_at_order TEXT,
    
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_order_item_product UNIQUE (order_id, product_id) -- Ensures a product appears only once per order; quantity reflects amount.
);

COMMENT ON TABLE order_items IS 'Stores individual items within an order.';
COMMENT ON COLUMN order_items.order_id IS 'Foreign key referencing the parent order.';
COMMENT ON COLUMN order_items.product_id IS 'Foreign key referencing the product ordered. ON DELETE RESTRICT to maintain order integrity.';
COMMENT ON COLUMN order_items.quantity IS 'Quantity of this product ordered.';
COMMENT ON COLUMN order_items.price_paid_per_unit IS 'Price of the product per unit at the time the order was placed.';
COMMENT ON COLUMN order_items.product_name_at_order IS 'Snapshot of product name at time of order for historical records.';
COMMENT ON COLUMN order_items.product_sku_at_order IS 'Snapshot of product SKU at time of order for historical records.';
COMMENT ON CONSTRAINT uq_order_item_product ON order_items IS 'Prevents adding the same product as multiple line items in the same order.';


-- Indexes
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_order_status ON orders(order_status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_orders_payment_intent_id ON orders(payment_intent_id);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);


-- Reusing or defining the trigger function for 'updated_at'
-- This should be defined once. If not already created by previous schema scripts, define it:
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'trigger_set_timestamp') THEN
    CREATE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $func$
    BEGIN
      NEW.updated_at = CURRENT_TIMESTAMP;
      RETURN NEW;
    END;
    $func$ LANGUAGE plpgsql;
  END IF;
END
$$;

-- Apply the trigger to new tables
CREATE TRIGGER set_timestamp_orders
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_timestamp_order_items
BEFORE UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

COMMIT;
```
