import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import apiClient from '../../../utils/api';
// For MVP, Module and Lesson forms might be inline or simple modals triggered here.
// import ModuleForm from '../../../components/admin/courses/ModuleForm'; 
// import LessonForm from '../../../components/admin/courses/LessonForm';

const AdminCourseEditPage = () => {
  const { courseId } = useParams(); // Undefined for 'new' course
  const navigate = useNavigate();
  const isEditing = Boolean(courseId);

  const [course, setCourse] = useState({
    title: '',
    description: '',
    instructor_id: '', // Will need a way to select this, or default for instructor role
    category_id: '',   // Will need a way to select this
    product_id: '',    // Optional
    level: '',
    duration_estimate: '',
    cover_image_url: '',
    is_published: false,
    slug: '', // Read-only for edit, generated by backend for new
  });
  
  const [modules, setModules] = useState([]); // For displaying modules of the current course
  // TODO: Add state for lessons of a selected module, selectedModuleId, etc.

  const [categories, setCategories] = useState([]); // To populate category dropdown
  const [users, setUsers] = useState([]); // To populate instructor dropdown (for admin)
  
  const [isLoading, setIsLoading] = useState(false);
  const [isFetchingDetails, setIsFetchingDetails] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);

  // --- Fetch initial data (course details if editing, categories, users) ---
  const fetchCourseDetails = useCallback(async () => {
    if (isEditing) {
      setIsFetchingDetails(true);
      setError(null);
      try {
        // This admin endpoint should fetch course with modules and lessons
        const response = await apiClient.get(`/admin/courses/${courseId}`);
        const fetchedCourse = response.data;
        setCourse({
            title: fetchedCourse.title || '',
            description: fetchedCourse.description || '',
            instructor_id: fetchedCourse.instructor_id || '',
            category_id: fetchedCourse.category_id || '',
            product_id: fetchedCourse.product_id || '',
            level: fetchedCourse.level || '',
            duration_estimate: fetchedCourse.duration_estimate || '',
            cover_image_url: fetchedCourse.cover_image_url || '',
            is_published: fetchedCourse.is_published || false,
            slug: fetchedCourse.slug || '', // Display slug
        });
        setModules(fetchedCourse.modules || []); // Assuming modules are nested in course details
      } catch (err) {
        console.error("Failed to fetch course details:", err);
        setError(err.response?.data?.message || 'Failed to load course data.');
      } finally {
        setIsFetchingDetails(false);
      }
    }
  }, [isEditing, courseId]);

  const fetchCategories = useCallback(async () => {
    // Assuming a public or admin endpoint for categories exists
    try {
      const response = await apiClient.get('/catalog/categories'); // Using public catalog endpoint
      setCategories(response.data || []);
    } catch (err) {
      console.error("Failed to fetch categories:", err);
      // setError("Could not load categories for selection."); // Minor error, don't block form
    }
  }, []);

  const fetchUsers = useCallback(async () => {
    // TODO: Implement this if admin needs to assign instructors.
    // For now, instructor_id might be pre-filled if user is instructor, or manually entered if admin.
    // This would typically fetch users with 'instructor' or 'admin' roles.
    // Example: const response = await apiClient.get('/admin/users?role=instructor');
    // setUsers(response.data.users);
    console.log("User fetching for instructor dropdown TBD.");
  }, []);


  useEffect(() => {
    fetchCourseDetails();
    fetchCategories();
    fetchUsers(); // Call this if implementing instructor selection for admin
  }, [fetchCourseDetails, fetchCategories, fetchUsers]);


  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setCourse(prevCourse => ({
      ...prevCourse,
      [name]: type === 'checkbox' ? checked : value,
    }));
  };

  const handleSubmitCourse = async (e) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);
    setSuccessMessage(null);

    // Basic validation (more robust validation should be added)
    if (!course.title.trim()) {
        setError("Title is required.");
        setIsLoading(false);
        return;
    }

    const payload = { ...course };
    // Remove slug from payload for new courses, backend generates it.
    // For existing, backend might ignore it or use it to check if title changed.
    if (!isEditing) delete payload.slug; 
    // Ensure category_id and product_id are null if empty string (or backend handles)
    if (payload.category_id === '') payload.category_id = null;
    if (payload.product_id === '') payload.product_id = null;
    // instructor_id: if user is instructor, backend should ensure they can only set it to self.
    // If admin, they can set it. Current setup assumes instructor_id is managed correctly or defaults in backend.


    try {
      let response;
      if (isEditing) {
        response = await apiClient.put(`/admin/courses/${courseId}`, payload);
        setSuccessMessage('Course updated successfully!');
      } else {
        response = await apiClient.post('/admin/courses', payload);
        setSuccessMessage('Course created successfully!');
        // After creating, navigate to edit page for the new course to add modules/lessons
        if (response.data.course && response.data.course.id) {
          navigate(`/admin/courses/${response.data.course.id}/edit`, { replace: true });
        } else {
            navigate('/admin/courses'); // Fallback
        }
      }
      // Optionally re-fetch details if staying on page after update
      if (isEditing) fetchCourseDetails();

    } catch (err) {
      console.error("Failed to save course:", err);
      setError(err.response?.data?.message || 'Failed to save course.');
    } finally {
      setIsLoading(false);
    }
  };

  // --- Placeholder functions for Module/Lesson CRUD ---
  // These would typically open modals or inline forms and call respective APIs
  const handleAddModule = () => alert('Add New Module functionality TBD.');
  const handleEditModule = (moduleId) => alert(`Edit Module ${moduleId} TBD.`);
  const handleDeleteModule = (moduleId) => alert(`Delete Module ${moduleId} TBD.`);
  const handleAddLesson = (moduleId) => alert(`Add New Lesson to Module ${moduleId} TBD.`);
  const handleEditLesson = (lessonId) => alert(`Edit Lesson ${lessonId} TBD.`);
  const handleDeleteLesson = (lessonId) => alert(`Delete Lesson ${lessonId} TBD.`);


  // Basic styling
  const styles = {
    container: { padding: '20px', fontFamily: 'Arial, sans-serif', maxWidth: '900px', margin: '0 auto' },
    header: { marginBottom: '20px' },
    formSection: { marginBottom: '30px', padding: '20px', border: '1px solid #eee', borderRadius: '8px' },
    formGroup: { marginBottom: '15px' },
    label: { display: 'block', marginBottom: '5px', fontWeight: 'bold' },
    input: { width: 'calc(100% - 18px)', padding: '8px', border: '1px solid #ccc', borderRadius: '4px' }, // Adjust width for padding/border
    textarea: { width: 'calc(100% - 18px)', padding: '8px', border: '1px solid #ccc', borderRadius: '4px', minHeight: '100px' },
    select: { width: '100%', padding: '8px', border: '1px solid #ccc', borderRadius: '4px' },
    checkboxLabel: { marginLeft: '5px' },
    button: { padding: '10px 20px', backgroundColor: '#007bff', color: 'white', border: 'none', borderRadius: '5px', cursor: 'pointer', marginRight: '10px' },
    error: { color: 'red', backgroundColor: '#ffe0e0', padding: '10px', borderRadius: '5px', margin: '10px 0'},
    success: { color: 'green', backgroundColor: '#e0ffe0', padding: '10px', borderRadius: '5px', margin: '10px 0'},
    loading: { textAlign: 'center', padding: '20px', fontSize: '1.2em' },
    sectionTitle: { marginTop: '30px', marginBottom: '15px', borderBottom: '1px solid #ccc', paddingBottom: '10px' },
    itemList: { listStyle: 'none', paddingLeft: 0 },
    item: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px dotted #eee' },
  };

  if (isEditing && isFetchingDetails) {
    return <div style={styles.loading}>Loading course details...</div>;
  }

  return (
    <div style={styles.container}>
      <Link to="/admin/courses" style={{display: 'inline-block', marginBottom: '20px'}}>&larr; Back to Courses</Link>
      <h1 style={styles.header}>{isEditing ? `Edit Course: ${course.title || ''}` : 'Create New Course'}</h1>

      {error && <div style={styles.error}>Error: {error}</div>}
      {successMessage && <div style={styles.success}>{successMessage}</div>}

      {/* --- Course Details Form --- */}
      <form onSubmit={handleSubmitCourse} style={styles.formSection}>
        <h2 style={{marginTop:0}}>Course Details</h2>
        <div style={styles.formGroup}>
          <label htmlFor="title" style={styles.label}>Title</label>
          <input type="text" name="title" id="title" value={course.title} onChange={handleChange} style={styles.input} required />
        </div>
        {isEditing && course.slug && (
          <div style={styles.formGroup}>
            <label htmlFor="slug" style={styles.label}>Slug (URL)</label>
            <input type="text" name="slug" id="slug" value={course.slug} style={styles.input} readOnly />
          </div>
        )}
        <div style={styles.formGroup}>
          <label htmlFor="description" style={styles.label}>Description</label>
          <textarea name="description" id="description" value={course.description} onChange={handleChange} style={styles.textarea}></textarea>
        </div>
        
        {/* TODO: Instructor ID - For admin, this should be a dropdown of users with 'instructor' role. 
            For an instructor, this field might be hidden or read-only showing themselves.
            For now, assuming it's an input or correctly defaulted by backend for instructor role.
        */}
        <div style={styles.formGroup}>
            <label htmlFor="instructor_id" style={styles.label}>Instructor ID (UUID)</label>
            <input type="text" name="instructor_id" id="instructor_id" value={course.instructor_id} onChange={handleChange} style={styles.input} placeholder="Manually enter instructor UUID for now" />
        </div>


        <div style={styles.formGroup}>
          <label htmlFor="category_id" style={styles.label}>Category</label>
          <select name="category_id" id="category_id" value={course.category_id} onChange={handleChange} style={styles.select}>
            <option value="">-- Select Category --</option>
            {categories.map(cat => (
              <option key={cat.id} value={cat.id}>{cat.name}</option>
            ))}
          </select>
        </div>
        <div style={styles.formGroup}>
          <label htmlFor="product_id" style={styles.label}>Linked Product ID (Optional UUID for paid course)</label>
          <input type="text" name="product_id" id="product_id" value={course.product_id} onChange={handleChange} style={styles.input} placeholder="e.g., UUID of a product"/>
        </div>
        <div style={styles.formGroup}>
          <label htmlFor="level" style={styles.label}>Level</label>
          <input type="text" name="level" id="level" value={course.level} onChange={handleChange} style={styles.input} placeholder="e.g., Beginner, Intermediate, Advanced"/>
        </div>
        <div style={styles.formGroup}>
          <label htmlFor="duration_estimate" style={styles.label}>Duration Estimate</label>
          <input type="text" name="duration_estimate" id="duration_estimate" value={course.duration_estimate} onChange={handleChange} style={styles.input} placeholder="e.g., Approx. 10 hours"/>
        </div>
        <div style={styles.formGroup}>
          <label htmlFor="cover_image_url" style={styles.label}>Cover Image URL</label>
          <input type="url" name="cover_image_url" id="cover_image_url" value={course.cover_image_url} onChange={handleChange} style={styles.input} placeholder="https://example.com/image.jpg"/>
        </div>
        <div style={styles.formGroup}>
          <input type="checkbox" name="is_published" id="is_published" checked={course.is_published} onChange={handleChange} />
          <label htmlFor="is_published" style={styles.checkboxLabel}>Published</label>
        </div>
        <button type="submit" disabled={isLoading} style={styles.button}>
          {isLoading ? 'Saving...' : (isEditing ? 'Update Course' : 'Create Course')}
        </button>
      </form>

      {/* --- Modules and Lessons Management (only if editing an existing course) --- */}
      {isEditing && courseId && (
        <>
          {/* Module Management Section */}
          <div style={styles.formSection}>
            <h2 style={styles.sectionTitle}>Modules</h2>
            <button onClick={handleAddModule} style={{...styles.button, backgroundColor: '#28a745', marginBottom: '15px'}}>Add New Module</button>
            {modules.length > 0 ? (
              <ul style={styles.itemList}>
                {modules.map(module => (
                  <li key={module.id} style={styles.item}>
                    <span>{module.module_order}. {module.title}</span>
                    <div>
                      <button onClick={() => handleEditModule(module.id)} style={{...styles.actionButton, backgroundColor: '#ffc107'}}>Edit</button>
                      <button onClick={() => handleDeleteModule(module.id)} style={{...styles.actionButton, backgroundColor: '#dc3545', color: 'white'}}>Delete</button>
                    </div>
                  </li>
                ))}
              </ul>
            ) : <p>No modules created yet for this course.</p>}
          </div>

          {/* Lesson Management Section - Placeholder, would typically show lessons for a selected module */}
          <div style={styles.formSection}>
            <h2 style={styles.sectionTitle}>Lessons (for selected module)</h2>
            <p>Lesson management UI will appear here once a module is selected or being edited.</p>
            {/* Example: if a module is selected: */}
            {/* <button onClick={() => handleAddLesson(selectedModuleId)} style={{...styles.button, backgroundColor: '#28a745', marginBottom: '15px'}}>Add New Lesson</button> */}
            {/* Display list of lessons for selectedModuleId */}
          </div>
        </>
      )}
      {/* TODO: ModuleForm and LessonForm components (likely modals or separate views) */}
    </div>
  );
};

export default AdminCourseEditPage;
